
server.port=8900

spring.cloud.config.environment.application=test-repo-service
eureka.client.serverUrl.defaultZone=http://eureka-server:8700/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.prefer-ip-address=true
