cloud:
  name: name from yml file cloud



MysQL:
  host: localhost
  port: 3307
  database: micro-mysql-db
  username: root
  password: root

spring:
  datasource:
  url: jdbc:mysql://${MysQL.host}:${MysQL.port}/${MysQL.database}?allowPublicKeyRetrieval=true&useSSL=false
  username: ${MysQL.username}
  password: ${MysQL.password}
  driver-class-name: com.mysql.cj.jdbc.Driver
  hikari:
    maximum-pool-size: 10
    minimum-idle: 5
    idle-timeout: 30000
    max-lifetime: 60000
    connection-timeout: 30000
jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
