spring.application.name=repo-rest
server.port=8900
eureka.client.serverUrl.defaultZone=http://eureka-server:8700/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.prefer-ip-address=true
