cloud:
  name: name from yml file 

  datasource:
    url: jdbc:mysql://${MysQL.host}:${MysQL.port}/${MysQL.database}
    username: ${MysQL.username}
    password: ${MysQL.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 30000

MysQL:
  host: mysql
  port: 3307
  database: micro-mysql-db
  username: root
  password: root

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
